from github import Github, Auth, GithubException
from typing import Dict, Optional

class GithubService:
    @staticmethod
    def push_to_github(token: str, repo_name: str, files: Dict[str, str], commit_message: str = "Deploy workflow") -> str:
        """
        Pushes files to the specified repository.
        repo_name can be "owner/repo" or just "repo" (implied user).
        Returns the HTML URL of the repository.
        """
        auth = Auth.Token(token)
        g = Github(auth=auth) # Using PyGithub
        
        user = g.get_user()
        
        repo = None
        try:
            # Try getting the repo potentially using full name
            repo = g.get_repo(repo_name)
        except GithubException:
            try:
                # If failed, maybe it is just a name and belongs to user?
                repo = user.get_repo(repo_name)
            except GithubException:
                # Create if it doesn't exist
                # Extract name if it contains slash
                name = repo_name.split("/")[-1]
                repo = user.create_repo(name, description="Auto-generated by UIBackend")
        
        if not repo:
            raise Exception("Could not find or create repository")

        # Push files
        for file_path, content in files.items():
            try:
                contents = repo.get_contents(file_path)
                repo.update_file(contents.path, commit_message, content, contents.sha)
            except GithubException:
                repo.create_file(file_path, commit_message, content)
                
        return repo.html_url
